build/pkgs/gap3/spkg-install.in: Use variables set by sage-spkg

diff --git a/build/pkgs/gap3/spkg-install.in b/build/pkgs/gap3/spkg-install.in
--- a/build/pkgs/gap3/spkg-install.in
+++ b/build/pkgs/gap3/spkg-install.in
@@ -4,13 +4,10 @@
 ## SETUP
 ###########################################
 
-PACKAGE_SHORTNAME=gap3
-VERSION=`cat package-version.txt`
-GAP3_DIR="gap-$VERSION"
-INSTALL_DIR="$SAGE_LOCAL/$PACKAGE_SHORTNAME/$GAP3_DIR/gap3"
+GAP3_DIR="gap-$PKG_VER"
+INSTALL_DIR="$SAGE_LOCAL/$PKG_BASE/$GAP3_DIR/gap3"
 
 echo "spkg-install is using"
-echo "VERSION = $VERSION"
 echo "GAP3_DIR = $GAP3_DIR"
 echo "INSTALL_DIR = $INSTALL_DIR"
 
@@ -28,7 +25,7 @@ sed -i.bak 's/ LOPTS="$(LOPTS) -static"/ LOPTS="$(LOPTS)"/g' src/src/Makefile
 cd src/src
 $MAKE
 if [ $? -ne 0 ]; then
-    echo >&2 "Error building $PACKAGE_SHORTNAME."
+    echo >&2 "Error building $PKG_BASE."
     exit 1
 fi
 cd ..
@@ -37,15 +34,15 @@ echo "Installing (copying) files..."
 mkdir -p "$INSTALL_DIR" &&
 cp -R -f * "$INSTALL_DIR"
 if [[ $? -ne 0 ]]; then
-    echo >&2 "Error copying $PACKAGE_SHORTNAME files."
+    echo >&2 "Error copying $PKG_BASE files."
     exit 1
 fi
 
-echo "Creating symlink to new $PACKAGE_SHORTNAME installation..."
-rm -f "$SAGE_LOCAL/$PACKAGE_SHORTNAME/latest"
-ln -s "$GAP3_DIR" "$SAGE_LOCAL/$PACKAGE_SHORTNAME/latest"
+echo "Creating symlink to new $PKG_BASE installation..."
+rm -f "$SAGE_LOCAL/$PKG_BASE/latest"
+ln -s "$GAP3_DIR" "$SAGE_LOCAL/$PKG_BASE/latest"
 if [[ $? -ne 0 ]]; then
-    echo >&2 "Error creating symbolic link '$SAGE_LOCAL/$PACKAGE_SHORTNAME/latest'"
+    echo >&2 "Error creating symbolic link '$SAGE_LOCAL/$PKG_BASE/latest'"
     exit 1
 fi
 
@@ -53,6 +50,6 @@ echo "Copying GAP3 startup script..."
 rm -f "$SAGE_LOCAL/bin/gap3"
 cp ../gap3.sh "$SAGE_LOCAL/bin/gap3"
 if [[ $? -ne 0 ]]; then
-    echo >&2 "Error copying customized $PACKAGE_SHORTNAME startup script."
+    echo >&2 "Error copying customized $PKG_BASE startup script."
     exit 1
 fi
