.github/workflows/dist-wheels-windows.yml: Windows continued

diff --git a/.github/workflows/dist-wheels-windows.yml b/.github/workflows/dist-wheels-windows.yml
--- a/.github/workflows/dist-wheels-windows.yml
+++ b/.github/workflows/dist-wheels-windows.yml
@@ -15,6 +15,8 @@ on:
       - '.github/workflows/dist.yml'
   merge_group:
   push:
+    branches:
+      - '*windows*'
     tags:
       # Match all release tags including beta, rc
       - 'passagemath-[0-9]+.[0-9]+'
@@ -45,7 +47,8 @@ jobs:
         uses: actions/cache@v4
         with:
           path: dist
-          key: sdists-${{ hashFiles('build/**', 'src/**', 'pkgs/**') }}
+          # FIXME: hashFiles returns empty
+          key: "sdists-${{ hashFiles('/build/**/*', '/src/**/*', '/pkgs/**/*') }}"
 
       - name: Install bootstrap prerequisites
         if: steps.cache-sdists.outputs.cache-hit != 'true'
@@ -60,7 +63,7 @@ jobs:
           path: |
             config.status
             local
-          key: sdists-SAGE_LOCAL-${{ hashFiles('build/**') }}
+          key: "sdists-SAGE_LOCAL-${{ hashFiles('/build/**/*') }}"
 
       - name: make pypi-sdists
         if: steps.cache-sdists.outputs.cache-hit != 'true'
@@ -85,24 +88,30 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - name: Cache sdists
-        id: cache-sdists
+
+      - name: Cache noarch-wheels
+        id: cache-noarch-wheels
         uses: actions/cache@v4
         with:
           path: dist
-          key: sdists-${{ hashFiles('build/**', 'src/**', 'pkgs/**') }}
+          # FIXME: hashFiles returns empty
+          key: "noarch-wheels-${{ hashFiles('/build/**/*', '/src/**/*', '/pkgs/**/*') }}"
 
       - name: Install bootstrap prerequisites
+        if: steps.cache-noarch-wheels.outputs.cache-hit != 'true'
         run: |
           sudo DEBIAN_FRONTEND=noninteractive apt-get update
           sudo DEBIAN_FRONTEND=noninteractive apt-get install $(build/bin/sage-get-system-packages debian _bootstrap)
+
       - name: make pypi-noarch-wheels
+        if: steps.cache-noarch-wheels.outputs.cache-hit != 'true'
         run: |
           ./bootstrap
           ./configure
           make pypi-noarch-wheels V=0
           (mkdir dist && mv venv/var/lib/sage/wheels/*sage*-none-any.whl dist/)
           ls -l dist
+
       - uses: actions/upload-artifact@v4
         with:
           path: "dist/*.whl"
@@ -174,9 +183,12 @@ jobs:
           install: >-
             mingw-w64-ucrt-x86_64-gcc
             autotools
+            mingw-w64-ucrt-x86_64-python
+            mingw-w64-ucrt-x86_64-python-pip
+            mingw-w64-ucrt-x86_64-python-setuptools
           msystem: ucrt64
           path-type: inherit
-        if: ${{ matrix.os == 'windows-2022' }}
+        if: matrix.os == 'windows-2022'
 
       - name: Download sdists
         uses: actions/download-artifact@v4
@@ -197,18 +209,38 @@ jobs:
         with:
           python-version: "3.10 - 3.12"
           update-environment: false
+        if: matrix.os != 'windows-2022'
+
+      - name: Retrieve configure tarball cache
+        id: cache-configure
+        uses: actions/cache/restore@v4
+        with:
+          path: |
+            build/pkgs/configure
+            upstream/configure*
+          key: "configure-${{ hashFiles('/build/**/*') }}"
 
       - name: Bootstrap
+        if: steps.cache-configure.outputs.cache-hit != 'true'
         # Patch python3 spkg-configure to allow Python 3.9.0 during the CIBW_BEFORE_ALL phase
         run: |
           export PATH=$(pwd)/build/bin:$PATH
           eval $(sage-print-system-package-command auto --sudo --yes update) || eval $(sage-print-system-package-command auto --yes update)
           eval $(sage-print-system-package-command auto --sudo --yes --no-install-recommends --spkg install _bootstrap bzip2 xz liblzma) || eval $(sage-print-system-package-command auto --yes --no-install-recommends --spkg install _bootstrap bzip2 xz liblzma)
           sed -i.bak '/m4_pushdef.*MIN_VERSION/s/3[0-9.]*/3.9.0/' build/pkgs/python3/spkg-configure.m4
-          ./bootstrap
+          ./bootstrap -s
         shell: msys2 {0}
 
-      - name: Cache SAGE_LOCAL
+      - name: Save configure tarball cache
+        if: steps.cache-configure.outputs.cache-hit != 'true'
+        uses: actions/cache/save@v4
+        with:
+          path: |
+            build/pkgs/configure
+            upstream/configure*
+          key: ${{ steps.cache-configure.outputs.cache-primary-key }}
+
+      - name: Retrieve SAGE_LOCAL cache
         id:   cache-sage-local
         uses: actions/cache/restore@v4
         with:
@@ -218,6 +250,7 @@ jobs:
           key: ${{ runner.os }}-cibuildwheel-${{ matrix.arch }}-${{ matrix.build }}
 
       - name: Unpack and prepare
+        id: unpack
         # We build the wheels from the sdists so that MANIFEST filtering becomes effective.
         # But we must run cibuildwheel with the unpacked source directory, not a tarball,
         # so that SAGE_ROOT is copied into the build containers.
@@ -234,12 +267,14 @@ jobs:
         #   SAGE_VENV must not be in PATH so it does not shadow cibuildwheel's build tools.
         #
         run: |
-          "${{ steps.python.outputs.python-path }}" -m pip install setuptools
+          if [ -n "${{ steps.python.outputs.python-path }}" ]; then "${{ steps.python.outputs.python-path }}" -m pip install setuptools; fi
           . ./.homebrew-build-env 2> /dev/null || :
-          ./configure --with-python="${{ steps.python.outputs.python-path }}" --with-system-python3=force --prefix=$HOME/runner-venv
+          if [ ! -x ./configure ]; then ./bootstrap -d; fi
+          status=0; ./configure --with-python="${{ steps.python.outputs.python-path || 'python3' }}" --with-system-python3=force --prefix=$HOME/runner-venv || status=$? || :
+          (echo ::group::config.log && cat config.log && echo ::endgroup:: && exit $status)
           make cibuildwheel
           export PATH=build/bin:$PATH
-          echo CIBW_BEFORE_ALL="echo > constraints.txt && ( $(sage-print-system-package-command debian update) && $(sage-print-system-package-command debian --yes --no-install-recommends install $(sage-get-system-packages debian $SPKGS) zip) || $(sage-print-system-package-command fedora --yes --no-install-recommends install $(sage-get-system-packages fedora $SPKGS | sed s/pkg-config/pkgconfig/) zip) || ( $(sage-print-system-package-command homebrew --yes --no-install-recommends install $(sage-get-system-packages homebrew $SPKGS)) || $(sage-print-system-package-command alpine --yes --no-install-recommends install $(sage-get-system-packages alpine $SPKGS) zip) || echo error ignored) ) && . ./.homebrew-build-env 2> /dev/null; rm -f config.status && PREFIX=${{ startsWith(matrix.os, 'ubuntu') && '/host/sage-\$AUDITWHEEL_PLAT' || '\$HOME/sage-local' }} && if cp \$PREFIX/config.status . 2>/dev/null; then chmod +x config.status; fi && if [ -x ./config.status ]; then ./config.status; else rm -f prefix && ./configure --enable-build-as-root --prefix=\$PREFIX --with-sage-venv --with-system-gfortran=force --with-system-python3=force --without-system-libpng && echo ::group::config.log && cat config.log && echo ::endgroup:: && cp config.status prefix/ && (MAKE=\"make -j6\" make -k V=0 $TARGETS_PRE || echo error ignored); fi && rm -rf prefix/lib/gap/pkg/{transgrp/data,ctbllib/data,tomlib/data,irredsol/data} prefix/share/gap/doc && for a in \$(find prefix/lib -type f -name 'lib*'); do case \$a in *flint*|*gf2x*|*gmp*|*gsl*|*mpfr*|*ntl*|*openblas*|*normaliz*) strip -x \$a;; esac; done; for a in \$(find prefix/bin -type f); do case \$a in *M2-binary*) strip -x \$a;; esac; done" >> "$GITHUB_ENV"
+          echo CIBW_BEFORE_ALL="echo > constraints.txt && ( $(sage-print-system-package-command debian update) && $(sage-print-system-package-command debian --yes --no-install-recommends install $(sage-get-system-packages debian $SPKGS) zip) || $(sage-print-system-package-command fedora --yes --no-install-recommends install $(sage-get-system-packages fedora $SPKGS | sed s/pkg-config/pkgconfig/) zip) || ( $(sage-print-system-package-command homebrew --yes --no-install-recommends install $(sage-get-system-packages homebrew $SPKGS)) || $(sage-print-system-package-command alpine --yes --no-install-recommends install $(sage-get-system-packages alpine $SPKGS) zip) || echo error ignored) ) && . ./.homebrew-build-env 2> /dev/null; rm -f config.status && PREFIX=${{ startsWith(matrix.os, 'ubuntu') && '/host/sage-\$AUDITWHEEL_PLAT' || '\$HOME/sage-local' }} && if cp \$PREFIX/config.status . 2>/dev/null; then chmod +x config.status; fi && if [ -x ./config.status ]; then ./config.status; else rm -f prefix && ./configure --enable-build-as-root --prefix=\$PREFIX --with-sage-venv --with-system-gfortran=force --with-system-python3=force --without-system-libpng; status=$?; echo ::group::config.log && cat config.log && echo ::endgroup:: && (exit $status) && cp config.status prefix/ && (MAKE=\"make -j6\" make -k V=0 $TARGETS_PRE || echo error ignored); fi && rm -rf prefix/lib/gap/pkg/{transgrp/data,ctbllib/data,tomlib/data,irredsol/data} prefix/share/gap/doc && for a in \$(find prefix/lib -type f -name 'lib*'); do case \$a in *flint*|*gf2x*|*gmp*|*gsl*|*mpfr*|*ntl*|*openblas*|*normaliz*) strip -x \$a;; esac; done; for a in \$(find prefix/bin -type f); do case \$a in *M2-binary*) strip -x \$a;; esac; done" >> "$GITHUB_ENV"
           mkdir -p unpacked
           for sdist in dist/$pkg*.tar.gz; do
               (cd unpacked && tar xfz - ) < $sdist
@@ -252,6 +287,7 @@ jobs:
           ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*objects*
 
       - name: Save SAGE_LOCAL cache
+        if:   (success() || failure()) && steps.unpack.outcome == 'success'
         uses: actions/cache/save@v4
         with:
           path: |
@@ -415,10 +451,10 @@ jobs:
     uses: ./.github/workflows/pypi-publish.yml
     secrets: inherit
 
-  tox:
-    needs: [sdists_for_pypi, noarch_wheels_for_pypi, build_wheels]
-    if: (success() || failure())
-    uses: ./.github/workflows/ci-wheels.yml
-    with:
-      run-id: ${{ github.run_id }}
-      oss: "['windows-2022']"
+  # tox:
+  #   needs: [sdists_for_pypi, noarch_wheels_for_pypi, build_wheels]
+  #   if: (success() || failure())
+  #   uses: ./.github/workflows/ci-wheels.yml
+  #   with:
+  #     run-id: ${{ github.run_id }}
+  #     oss: "['windows-2022']"
