.github/workflows/dist.yml (wheels): Split into 2 jobs < 6h

diff --git a/.github/workflows/dist.yml b/.github/workflows/dist.yml
--- a/.github/workflows/dist.yml
+++ b/.github/workflows/dist.yml
@@ -201,7 +201,7 @@ jobs:
       # SPKGs to install as system packages
       SPKGS: _bootstrap _prereq openssl curl readline liblzma libffi bzip2 zlib info libxml2 gdbm ${{ startsWith(matrix.os, 'macos') && 'gfortran' || '' }}
       # Non-Python packages to install as spkgs
-      TARGETS_PRE: ccache libpng gmp mpfr mpc bliss coxeter3 mcqd meataxe sirocco boost_cropped tdlib brial cliquer giac glpk libhomfly gsl pari ntl flint linbox iml lcalc libbraiding m4ri m4rie planarity rw symmetrica singular eclib gap ecl maxima libgd msolve cddlib latte_int 4ti2 topcom palp nauty qepcad gfan frobby lrslib sympow elliptic_curves rubiks plantri buckygen benzene macaulay2 glucose kissat pip
+      TARGETS_PRE: ccache libpng gmp mpfr mpc boost_cropped brial cliquer giac glpk libhomfly gsl pari ntl flint linbox iml lcalc libbraiding m4ri m4rie planarity rw symmetrica singular eclib gap ecl maxima libgd  cddlib  palp nauty gfan sympow elliptic_curves pip
       CIBW_BUILD: "*${{ matrix.build }}*"
       # Disable building PyPy wheels on all platforms
       CIBW_SKIP: "pp*"
@@ -293,7 +293,6 @@ jobs:
         #   SAGE_LOCAL is put in PATH for the wheel building.
         #   SAGE_VENV must not be in PATH so it does not shadow cibuildwheel's build tools.
         #
-        # omit sagemath-{meataxe,sirocco} for now -- needs sagemath-modules
         run: |
           "${{ steps.python.outputs.python-path }}" -m pip install setuptools
           . ./.homebrew-build-env 2> /dev/null || :
@@ -326,43 +325,17 @@ jobs:
         run: |
           ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*categories*
 
-      - name: sagemath-bliss
-        id:   sagemath-bliss
-        if:   (success() || failure()) && steps.sagemath-categories.outcome == 'success'
-        run: |
-          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*bliss*
-
       - name: sagemath-brial
         id:   sagemath-brial
         if:   (success() || failure()) && steps.sagemath-categories.outcome == 'success'
         run: |
           ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*brial*
 
-      - name: sagemath-coxeter3
-        id:   sagemath-coxeter3
-        if:   (success() || failure()) && steps.sagemath-categories.outcome == 'success'
-        run: |
-          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*coxeter3*
-
       - name: sagemath-giac
         id:   sagemath-giac
         if:   (success() || failure()) && steps.sagemath-categories.outcome == 'success'
         run: |
           ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*giac*
-
-      - name: sagemath-mcqd
-        id:   sagemath-mcqd
-        if:   (success() || failure()) && steps.sagemath-categories.outcome == 'success'
-        run: |
-          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*mcqd*
-
-      - name: sagemath-tdlib
-        id:   sagemath-tdlib
-        run: |
-          case "${{ matrix.arch }}" in
-              i686) ;;  # broken - boost-related
-              *) ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*tdlib*
-          esac
 
       - name: sagemath-glpk
         id:   sagemath-glpk
@@ -438,47 +411,17 @@ jobs:
         run: |
           ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*flint*
 
-      - name: sagemath-msolve
-        id:   sagemath-msolve
-        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
-        run: |
-          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*msolve*
-
       - name: sagemath-cddlib
         id:   sagemath-cddlib
         if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
         run: |
           ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*cddlib*
 
-      - name: sagemath-latte-4ti2
-        id:   sagemath-latte-4ti2
-        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
-        run: |
-          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*latte*4ti2*
-
-      - name: sagemath-topcom
-        id:   sagemath-topcom
-        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
-        run: |
-          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*topcom*
-
       - name: sagemath-gfan
         id:   sagemath-gfan
         if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
         run: |
           ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*gfan*
-
-      - name: sagemath-lrslib
-        id:   sagemath-lrslib
-        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
-        run: |
-          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*lrslib*
-
-      - name: sagemath-frobby
-        id:   sagemath-frobby
-        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
-        run: |
-          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*frobby*
 
       - name: sagemath-palp
         id:   sagemath-palp
@@ -491,12 +434,6 @@ jobs:
         if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
         run: |
           ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*nauty*
-
-      - name: sagemath-qepcad
-        id:   sagemath-qepcad
-        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
-        run: |
-          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*qepcad*
 
       - name: sagemath-linbox
         id:   sagemath-linbox
@@ -564,17 +501,232 @@ jobs:
         run: |
           ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*standard*no*symbolics*
 
-      - name: sagemath-rubiks
-        id:   sagemath-rubiks
-        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
-        run: |
-          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath_rubiks*
-
       - name: sagemath-cliquer
         id:   sagemath-cliquer
         if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
         run: |
           ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath_cliquer*
+
+
+      - uses: actions/upload-artifact@v4
+        if:   always()
+        with:
+          name: ${{ matrix.os }}-${{ matrix.build }}-${{ matrix.arch }}-wheels
+          path: ./wheelhouse/*.whl
+
+  build_optional_wheels:
+    name: wheels ${{ matrix.build }}*_${{ matrix.arch }} optional
+    runs-on: ${{ matrix.os }}
+    needs: [sdists_for_pypi, noarch_wheels_for_pypi, build_wheels]
+    strategy:
+      fail-fast: false
+      matrix:
+        os:      [ubuntu-latest]
+        arch: >-
+          ${{ github.event_name == 'pull_request'
+                && fromJson('["x86_64"]')
+                || fromJson('["x86_64", "i686"]') }}
+        build: >-
+          ${{ github.event_name == 'pull_request'
+                && fromJson('["manylinux"]')
+                || fromJson('["manylinux", "musllinux"]') }}
+        include:
+          - os: macos-13
+            arch: x86_64
+            build: macosx
+          - os: macos-14
+            arch: arm64
+            build: macosx
+    env:
+      CAN_DEPLOY: ${{ secrets.SAGEMATH_PYPI_API_TOKEN != '' }}
+      # SPKGs to install as system packages
+      SPKGS: _bootstrap _prereq openssl curl readline liblzma libffi bzip2 zlib info libxml2 gdbm ${{ startsWith(matrix.os, 'macos') && 'gfortran' || '' }}
+      # Non-Python packages to install as spkgs
+      TARGETS_PRE: ccache libpng gmp mpfr mpc bliss coxeter3 mcqd meataxe sirocco boost_cropped tdlib brial cliquer giac glpk libhomfly gsl pari ntl flint linbox iml lcalc libbraiding m4ri m4rie planarity rw symmetrica singular eclib gap ecl maxima libgd msolve cddlib latte_int 4ti2 topcom palp nauty qepcad gfan frobby lrslib sympow elliptic_curves rubiks plantri buckygen benzene macaulay2 glucose kissat pip
+      CIBW_BUILD: "*${{ matrix.build }}*"
+      # Disable building PyPy wheels on all platforms
+      CIBW_SKIP: "pp*"
+      #
+      CIBW_ARCHS: ${{ matrix.arch }}
+      # https://cibuildwheel.readthedocs.io/en/stable/options/#requires-python
+      CIBW_PROJECT_REQUIRES_PYTHON: ${{ github.event_name == 'pull_request' && '>=3.9, <3.11' || '>=3.9, <3.13' }}
+      # Run before wheel build
+      CIBW_BEFORE_BUILD: |
+        (echo "passagemath-conf @ file://$(pwd)/pkgs/sage-conf" && echo "passagemath-setup @ file://$(pwd)/pkgs/sage-setup" && echo "cysignals < 1.12") > constraints.txt
+      # Environment during wheel build
+      CIBW_ENVIRONMENT: "PATH=$(pwd)/prefix/bin:$PATH CPATH=$(pwd)/prefix/include:$CPATH LIBRARY_PATH=$(pwd)/prefix/lib:$LIBRARY_PATH PKG_CONFIG_PATH=$(pwd)/prefix/lib/pkgconfig:$PKG_CONFIG_PATH ACLOCAL_PATH=/usr/share/aclocal PIP_CONSTRAINT=$(pwd)/constraints.txt PIP_FIND_LINKS=file://$(pwd)/wheelhouse' 'file://$(pwd)/dist SAGE_NUM_THREADS=6 ${{ startsWith(matrix.os, 'macos') && 'FC=gfortran-14 LDFLAGS=\"-Wl,-ld_classic -Wl,-headerpad_max_install_names $LDFLAGS\"' || '' }}"
+      # Use 'build', not 'pip wheel'
+      CIBW_BUILD_FRONTEND: build
+      # Without setting LD_LIBRARY_PATH, we get Cannot repair wheel, because required library "libm4ri-0.0.20200125.so" could not be located
+      CIBW_REPAIR_WHEEL_COMMAND_LINUX: "set -x && export LD_LIBRARY_PATH=$(pwd)/prefix/lib:$LD_LIBRARY_PATH && pkg=$(basename {wheel}) && pkg=${pkg%%-*} && pkg=${pkg//_/-} && pkg=${pkg#pas} && if [ -r pkgs/$pkg/repair_wheel.py ]; then python3 -m pip install passagemath-conf && python3 pkgs/$pkg/repair_wheel.py {wheel}; fi && auditwheel repair -w {dest_dir} {wheel}"
+      # to avoid "DelocationError: Library dependencies do not satisfy target MacOS version 10.9"
+      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.os == 'macos-13' && '13.0' || '14.0' }}
+      # Avoid onetbb build failure on manylinux2014 (https://github.com/passagemath/passagemath/issues/460)
+      # manylinux_2_28 will be default from May 2025 - https://cibuildwheel.pypa.io/en/stable/options/#linux-image
+      CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
+    steps:
+      - name: Maximize build disk space
+        if: runner.os == 'Linux'
+        uses: easimon/maximize-build-space@v10
+        with:
+          # need space in /var for Docker images
+          root-reserve-mb:      30000
+          remove-dotnet:        true
+          remove-android:       true
+          remove-haskell:       true
+          remove-codeql:        true
+          remove-docker-images: true
+
+      - uses: actions/checkout@v4
+
+      - name: Set up QEMU
+        if: runner.os == 'Linux' && matrix.arch != 'x86_64' && matrix.arch != 'i686'
+        uses: docker/setup-qemu-action@v3
+        with:
+          platforms: all
+
+      - uses: actions/download-artifact@v4
+        with:
+          name: dist
+          path: dist
+
+      - uses: actions/download-artifact@v4
+        with:
+          name: noarch-wheels
+          path: dist
+
+      - uses: actions/download-artifact@v4
+        with:
+          name: ${{ matrix.os }}-${{ matrix.build }}-${{ matrix.arch }}-wheels
+          path: dist
+
+      - uses: actions/setup-python@v5
+        # As of 2024-02-03, the macOS M1 runners do not have preinstalled python or pipx.
+        # Installing pipx follows the approach of https://github.com/pypa/cibuildwheel/pull/1743
+        id: python
+        with:
+          python-version: "3.8 - 3.12"
+          update-environment: false
+
+      - name: Bootstrap
+        run: |
+          export PATH=$(pwd)/build/bin:$PATH
+          eval $(sage-print-system-package-command auto --sudo --yes --no-install-recommends --spkg install _bootstrap)
+          ./bootstrap
+
+      - name: Cache SAGE_LOCAL
+        id:   cache-sage-local
+        uses: actions/cache/restore@v4
+        with:
+          path: |
+            /sage-*
+            ~/sage-*
+          key: ${{ runner.os }}-cibuildwheel-${{ matrix.arch }}-${{ matrix.build }}
+
+      - name: Unpack and prepare
+        # We build the wheels from the sdists so that MANIFEST filtering becomes effective.
+        # But we must run cibuildwheel with the unpacked source directory, not a tarball,
+        # so that SAGE_ROOT is copied into the build containers.
+        #
+        # In the CIBW_BEFORE_ALL phase, we install libraries using the Sage distribution.
+        # https://cibuildwheel.readthedocs.io/en/stable/options/#before-all
+        # For Linux, this is repeated for each of the packages that we build wheels for
+        # because CIBW starts with a fresh container on each invocation.
+        # Therefore we cache it in a directory mounted from the host: /host
+        # https://cibuildwheel.pypa.io/en/stable/faq/#linux-builds-in-containers
+        #
+        # - configure --with-sage-venv makes the SAGE_VENV separate from SAGE_LOCAL.
+        #   SAGE_LOCAL is put in PATH for the wheel building.
+        #   SAGE_VENV must not be in PATH so it does not shadow cibuildwheel's build tools.
+        #
+        run: |
+          "${{ steps.python.outputs.python-path }}" -m pip install setuptools
+          . ./.homebrew-build-env 2> /dev/null || :
+          ./configure --with-python="${{ steps.python.outputs.python-path }}" --with-system-python3=force --prefix=$HOME/runner-venv
+          make cibuildwheel
+          export PATH=build/bin:$PATH
+          echo CIBW_BEFORE_ALL="echo > constraints.txt && ( $(sage-print-system-package-command debian --yes --no-install-recommends install $(sage-get-system-packages debian $SPKGS) zip) || $(sage-print-system-package-command fedora --yes --no-install-recommends install $(sage-get-system-packages fedora $SPKGS | sed s/pkg-config/pkgconfig/) zip) || ( $(sage-print-system-package-command homebrew --yes --no-install-recommends install $(sage-get-system-packages homebrew $SPKGS)) || $(sage-print-system-package-command alpine --yes --no-install-recommends install $(sage-get-system-packages alpine $SPKGS) zip) || echo error ignored) ) && rm -f config.status && PREFIX=${{ startsWith(matrix.os, 'ubuntu') && '/host/sage-\$AUDITWHEEL_PLAT' || '\$HOME/sage-local' }} && if cp \$PREFIX/config.status . 2>/dev/null; then chmod +x config.status; fi && if [ -x ./config.status ]; then ./config.status; else ./configure --enable-build-as-root --prefix=\$PREFIX --with-sage-venv --with-system-gfortran=force --without-system-libpng && cat config.log && cp config.status prefix/ && (MAKE=\"make -j6\" make -k V=0 $TARGETS_PRE || echo error ignored); fi && rm -rf prefix/lib/gap/pkg/{transgrp/data,ctbllib/data,tomlib/data,irredsol/data} prefix/share/gap/doc" >> "$GITHUB_ENV"
+          mkdir -p unpacked
+          for sdist in dist/$pkg*.tar.gz; do
+              (cd unpacked && tar xfz - ) < $sdist
+          done
+
+      - name: sagemath-bliss
+        id:   sagemath-bliss
+        if:   (success() || failure()) && steps.sagemath-categories.outcome == 'success'
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*bliss*
+
+      - name: sagemath-coxeter3
+        id:   sagemath-coxeter3
+        if:   (success() || failure()) && steps.sagemath-categories.outcome == 'success'
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*coxeter3*
+
+      - name: sagemath-mcqd
+        id:   sagemath-mcqd
+        if:   (success() || failure()) && steps.sagemath-categories.outcome == 'success'
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*mcqd*
+
+      - name: sagemath-meataxe
+        id:   sagemath-meataxe
+        if:   (success() || failure()) && steps.sagemath-categories.outcome == 'success'
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*meataxe*
+
+      - name: sagemath-sirocco
+        id:   sagemath-sirocco
+        if:   (success() || failure()) && steps.sagemath-categories.outcome == 'success'
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*sirocco*
+
+      - name: sagemath-tdlib
+        id:   sagemath-tdlib
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*tdlib*
+
+      - name: sagemath-msolve
+        id:   sagemath-msolve
+        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*msolve*
+
+      - name: sagemath-latte-4ti2
+        id:   sagemath-latte-4ti2
+        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*latte*4ti2*
+
+      - name: sagemath-topcom
+        id:   sagemath-topcom
+        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*topcom*
+
+      - name: sagemath-lrslib
+        id:   sagemath-lrslib
+        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*lrslib*
+
+      - name: sagemath-frobby
+        id:   sagemath-frobby
+        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*frobby*
+
+      - name: sagemath-qepcad
+        id:   sagemath-qepcad
+        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*qepcad*
+
+      - name: sagemath-rubiks
+        id:   sagemath-rubiks
+        if:   (success() || failure()) && steps.sagemath-modules.outcome == 'success'
+        run: |
+          ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath_rubiks*
 
       - name: sagemath-plantri
         id:   sagemath-plantri
@@ -613,15 +765,17 @@ jobs:
           ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath_macaulay2*
 
 
+
       - uses: actions/upload-artifact@v4
         if:   always()
         with:
-          name: ${{ matrix.os }}-${{ matrix.build }}-${{ matrix.arch }}-wheels
+          name: ${{ matrix.os }}-${{ matrix.build }}-${{ matrix.arch }}-optional-wheels
           path: ./wheelhouse/*.whl
+
 
   upload_wheels:
     # This needs to be a separate job because pypa/gh-action-pypi-publish cannot run on macOS
-    needs: [sdists_for_pypi, noarch_wheels_for_pypi, build_wheels]
+    needs: [sdists_for_pypi, noarch_wheels_for_pypi, build_wheels, build_optional_wheels]
     if: (success() || failure()) && startsWith(github.ref, 'refs/tags')
 
     runs-on: ubuntu-latest
@@ -656,7 +810,7 @@ jobs:
         if: env.CAN_DEPLOY == 'true'
 
   tox:
-    needs: [sdists_for_pypi, noarch_wheels_for_pypi, build_wheels]
+    needs: [sdists_for_pypi, noarch_wheels_for_pypi, build_wheels, build_optional_wheels]
     if: (success() || failure())
     uses: ./.github/workflows/ci-wheels.yml
     with:
