.github/workflows/dist-wheels-windows.yml: Windows continued

diff --git a/.github/workflows/dist-wheels-windows.yml b/.github/workflows/dist-wheels-windows.yml
--- a/.github/workflows/dist-wheels-windows.yml
+++ b/.github/workflows/dist-wheels-windows.yml
@@ -143,7 +143,7 @@ jobs:
       CIBW_BEFORE_BUILD: |
         (echo "passagemath-conf @ file://$(pwd)/pkgs/sage-conf" && echo "passagemath-setup @ file://$(pwd)/pkgs/sage-setup") > constraints.txt
       # Environment during wheel build
-      CIBW_ENVIRONMENT: "PATH=$(pwd)/prefix/bin:$PATH CPATH=$(pwd)/prefix/include:$CPATH LIBRARY_PATH=$(pwd)/prefix/lib:$LIBRARY_PATH PKG_CONFIG_PATH=$(pwd)/prefix/lib/pkgconfig:$PKG_CONFIG_PATH ACLOCAL_PATH=/usr/share/aclocal LINBOX_CONFIGURE=--without-ntl GIAC_CONFIGURE=--disable-ntl SAGE_MACAULAY2_BUILD_OPTIONS=-DWITH_PYTHON=off PIP_CONSTRAINT=$(pwd)/constraints.txt PIP_FIND_LINKS=file://$(pwd)/wheelhouse' 'file://$(pwd)/dist SAGE_NUM_THREADS=6 ${{ startsWith(matrix.os, 'macos') && 'FC=gfortran-14 LDFLAGS=\"-Wl,-ld_classic -Wl,-headerpad_max_install_names $LDFLAGS\"' || '' }}"
+      CIBW_ENVIRONMENT: "PATH=$(pwd)/prefix/bin:$(pwd)/build/bin:$PATH CPATH=$(pwd)/prefix/include:$CPATH LIBRARY_PATH=$(pwd)/prefix/lib:$LIBRARY_PATH PKG_CONFIG_PATH=$(pwd)/prefix/lib/pkgconfig:$PKG_CONFIG_PATH ACLOCAL_PATH=/usr/share/aclocal LINBOX_CONFIGURE=--without-ntl GIAC_CONFIGURE=--disable-ntl SAGE_MACAULAY2_BUILD_OPTIONS=-DWITH_PYTHON=off PIP_CONSTRAINT=$(pwd)/constraints.txt PIP_FIND_LINKS=file://$(pwd)/wheelhouse' 'file://$(pwd)/dist MAKEFLAGS=-j6 SAGE_NUM_THREADS=6 ${{ startsWith(matrix.os, 'macos') && 'FC=gfortran-14 LDFLAGS=\"-Wl,-ld_classic -Wl,-headerpad_max_install_names $LDFLAGS\"' || '' }}"
       # Use 'build', not 'pip wheel'
       CIBW_BUILD_FRONTEND: build
       # Without setting LD_LIBRARY_PATH, we get Cannot repair wheel, because required library "libm4ri-0.0.20200125.so" could not be located
@@ -276,7 +276,9 @@ jobs:
           # (echo && echo ::group::config.log && cat config.log && echo ::endgroup:: && exit $status)
           # make cibuildwheel V=0
           export PATH=build/bin:$PATH
-          echo CIBW_BEFORE_ALL="msys2 -c 'echo > constraints.txt && ( $(sage-print-system-package-command debian update) && $(sage-print-system-package-command debian --yes --no-install-recommends install $(sage-get-system-packages debian $SPKGS) zip) || $(sage-print-system-package-command fedora --yes --no-install-recommends install $(sage-get-system-packages fedora $SPKGS | sed s/pkg-config/pkgconfig/) zip) || ( $(sage-print-system-package-command homebrew --yes --no-install-recommends install $(sage-get-system-packages homebrew $SPKGS)) || $(sage-print-system-package-command alpine --yes --no-install-recommends install $(sage-get-system-packages alpine $SPKGS) zip) || echo error ignored) ) && . ./.homebrew-build-env 2> /dev/null; rm -f config.status && PREFIX=${{ startsWith(matrix.os, 'ubuntu') && '/host/sage-\$AUDITWHEEL_PLAT' || '\$HOME/sage-local' }} && if cp \$PREFIX/config.status . 2>/dev/null; then chmod +x config.status; fi && if [ -x ./config.status ]; then ./config.status; else rm -f prefix && ./configure --enable-build-as-root --prefix=\$PREFIX --with-sage-venv --with-system-gfortran=force --with-system-python3=force --without-system-libpng; status=$?; echo && echo ::group::config.log && cat config.log && echo ::endgroup:: && (exit $status) && cp config.status prefix/ && (MAKE=\"make -j6\" make -k V=0 $TARGETS_PRE || echo error ignored); fi && rm -rf prefix/lib/gap/pkg/{transgrp/data,ctbllib/data,tomlib/data,irredsol/data} prefix/share/gap/doc && for a in \$(find prefix/lib -type f -name 'lib*'); do case \$a in *flint*|*gf2x*|*gmp*|*gsl*|*mpfr*|*ntl*|*openblas*|*normaliz*) strip -x \$a;; esac; done; for a in \$(find prefix/bin -type f); do case \$a in *M2-binary*) strip -x \$a;; esac; done'" >> "$GITHUB_ENV"
+          # echo CIBW_BEFORE_ALL="msys2 -c \"echo > constraints.txt && ( eval \\\$(sage-print-system-package-command auto update) && eval \\\$(sage-print-system-package-command auto --yes --spkg --no-install-recommends install $SPKGS) || echo error ignored ) && rm -f config.status && PREFIX=\\\$HOME/sage-local && if cp \\\$PREFIX/config.status . 2>/dev/null; then chmod +x config.status; fi && if [ -x ./config.status ]; then ./config.status; else rm -f prefix && ./configure --enable-build-as-root --prefix=\\\$PREFIX --with-sage-venv --with-system-gfortran=force --with-system-python3=force --without-system-libpng; status=$?; echo && echo ::group::config.log && cat config.log && echo ::endgroup:: && (exit \\\$status) && cp config.status prefix/ && (make -k V=0 $TARGETS_PRE || echo error ignored); fi && rm -rf prefix/lib/gap/pkg/{transgrp/data,ctbllib/data,tomlib/data,irredsol/data} prefix/share/gap/doc && for a in \\\$(find prefix/lib -type f -name 'lib*'); do case \\\$a in *flint*|*gf2x*|*gmp*|*gsl*|*mpfr*|*ntl*|*openblas*|*normaliz*) strip -x \\\$a;; esac; done; for a in \\\$(find prefix/bin -type f); do case \\\$a in *M2-binary*) strip -x \\\$a;; esac; done\"" >> "$GITHUB_ENV"
+          ### above fails - quoting puzzle
+          echo CIBW_BEFORE_ALL="msys2 -c \"echo > constraints.txt && ( echo ignored )\"" >> "$GITHUB_ENV"
           mkdir -p unpacked
           set -x
           for sdist in dist/$pkg*.tar.gz; do
@@ -293,16 +295,14 @@ jobs:
             ~/sage-*
           key: ${{ steps.cache-sage-local.outputs.cache-primary-key }}
 
-      - name: Build wheels
+      - name: sagemath-objects
+        id:   sagemath-objects
         uses: pypa/cibuildwheel@v2.23.0
         with:
           package-dir: unpacked/passagemath_objects
-
-      ## - name: sagemath-objects
-      ##   id:   sagemath-objects
-      ##   run: |
-      ##     ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*objects*
-      ##   shell: msys2 {0}
+        ## run: |
+        ##   ~/runner-venv/bin/python3 -m cibuildwheel unpacked/*sagemath*objects*
+        ## shell: msys2 {0}
 
       - name: Save SAGE_LOCAL cache again
         if:   (success() || failure()) && steps.unpack.outcome == 'success'
